- CONTRIBUTING.md
Basic description and location of our thrice-weekly Standup meetings.
> Standup times

- ux-design/sprint0StakeholderDemoScript.md
Please review this script for the stakeholder demo. Make edits as you see fit.
> Basic script for demo

- TOS.md
Generated using an [online service](https://www.privacypolicies.com) that generates draft TOS. Not legal advice etc etc, but good enough for a college project.
> First draft of terms of service

- front-end/package-lock.json
- front-end/package.json
- front-end/src/App.js
- front-end/src/Home.js
> Set up Router in App.js

- README.md
- front-end/README.md
- front-end/package-lock.json
READMEs now reference npm install.
> Frontend ReadMe

- front-end/src/App.css
- front-end/src/App.js
- front-end/src/Footer.js
- front-end/src/Home.js
- front-end/src/MeetTheTeam.js
- front-end/src/TermsOfService.js
> Create Site Footer

- front-end/package-lock.json
- front-end/package.json
- front-end/src/App.css
- front-end/src/Hamburger.js
- front-end/src/Home.js
- front-end/src/MeetTheTeam.js
- front-end/src/TermsOfService.js
Currently points to meet the team and terms of service, but will be changed to point to Profile and Shows once those pages exist.
Uses colors from [the palette](https://github.com/agile-dev-assignments/project-setup-team-hatsukaichi-dynamic/blob/master/front-end/palette.png).
> Functional hamburger menu

- front-end/src/TermsOfService.css
- front-end/src/TermsOfService.js
TermsOfService.js and TermsOfService.css filled out
> Terms of Service Added

- front-end/src/App.css
Only a fix for home, not for others.
> Fix for white space on home screen top

- front-end/src/TermsOfService.css
- front-end/src/TermsOfService.js
#27 Adds a table of contents at the top of the ToS page with links to each section.
> added links to headers in ToS

- front-end/package-lock.json
- front-end/package.json
- front-end/src/Profile.js
Using react-copy-to-clipboard. Applies to #66
> Functional share button

- front-end/src/App.js
- front-end/src/MockData.js
- front-end/src/MyShows.css
- front-end/src/MyShows.js
- front-end/src/Profile.js
> Create My Shows Page

- front-end/src/Profile.css
- front-end/src/Profile.js
> Functional buttons

- front-end/src/MyShows.js
fixes #85, which gives background on the issue.
> Reduce API Calls when filtering

- front-end/package-lock.json
- front-end/package.json
- front-end/src/App.js
- front-end/src/Profile.css
- front-end/src/Profile.js
For #40 
Still working on the inputs, buttons, forms, etc.
> Settings modal

- front-end/src/Hamburger.js
Currently links to user with id 1 as a placeholder.
> Hamburger links to proper routes

- front-end/src/App.css
- front-end/src/Header.css
- front-end/src/HeaderLogo.css
- front-end/src/HeaderLogo.js
- front-end/src/MyShows.css
- front-end/src/MyShows.js
- front-end/src/Profile.css
- front-end/src/Profile.js
fixes #89 
Plus some styling fixes and class/id renaming to avoid styling conflicts.
> Reduce API Calls after Settings are updated

- front-end/package-lock.json
- front-end/src/MockData.js
- front-end/src/MyShows.css
- front-end/src/MyShows.js
> 31-filter-modal

- CONTRIBUTING.md
> Clearer guidelines for naming

- front-end/src/MyShows.js
> Each show links to its individual show page

- front-end/src/App.js
- front-end/src/IndividualShow.js
- front-end/src/MyShows.js
> Connect individual show page to search results

- back-end/app.js
- back-end/package-lock.json
- back-end/package.json
- back-end/server.js
Group work during in-class Express.js workshop
resolves #100
> Create GET route for individual show

- README.md
- front-end/.env
- front-end/package-lock.json
- front-end/package.json
- front-end/src/App.js
- front-end/src/IndividualShow.js
- front-end/src/MeetTheTeam.js
- front-end/src/MyShows.js
- front-end/src/Profile.js
- front-end/src/Signup.js
Uses dotenv to manage API keys.
Solves #155
> dotenv mockaroo key

- back-end/app.js
#103 Create GET route for individual user
> GET route for individual user

- front-end/src/App.css
- front-end/src/IndividualShow.css
- front-end/src/MyShows.css
- front-end/src/TermsOfService.css
- front-end/src/TermsOfService.js
Partially solves #161:
*  I think having the fields change color when you mouse over them in the settings modal/individual show page is disorienting. It makes it a bit hard to actually interact with the settings/individual show. FIXED
* The individual show page looks good, but I think it's far too spaced out; I don't think this is a screen for which you should have to scroll to see everything. FIXED
* The logo link in the header extends too far
* The vertical spacing between elements is too large on my shows
* For pages without much content on them, the footer should be at the bottom of the screen; there shouldn't be empty space below it.
> Further fixes

- front-end/src/App.js
- front-end/src/Login.js
- front-end/src/Profile.js
> Manage Logged In User State

- front-end/src/Profile.js
> Link Profile Recent Shows to Show Pages

- front-end/src/App.js
- front-end/src/Header.js
- front-end/src/LogoutButton.css
- front-end/src/LogoutButton.js
> Alternate Login/Signup Buttons with Logout Button

- front-end/src/Profile.js
> Show Settings only for profile's user (logged in)

- README.md
- back-end/app.js
- back-end/package-lock.json
- back-end/package.json
> Dotenv backend

- back-end/app.js
get request to shows-trakt without query shows popular shows [here](https://slack-files.com/T01LN2C2L20-F01T4HR3Z53-5c1bf9d722)
get request to shows-trakt with a query (show or movie query) shows requested show/movie information [here](https://slack-files.com/T01LN2C2L20-F01TL8QN057-111b08cbda)
> Get shows route with Trakt API

- back-end/package-lock.json
- back-end/package.json
- back-end/test/getShows.js
draft for now, will resolve #212
> Add Unit Tests for GET /shows

- back-end/test/patchUsers.js
#217 Add unit test for patch user route
> Patch user route unit test

- back-end/server.js
> Change back-end port to avoid conflict with front-end

- .gitignore
- back-end/MockData.js
- back-end/app.js
- back-end/test/getShow.js
- back-end/test/getShows.js
- back-end/test/getUsers.js
- back-end/test/patchUsers.js
> Return mock data from API when Mockaroo gives 500

- back-end/app.js
looks like somehow a `})` ended up missing in `App.js`, I'm adding it back in with this PR
> Fix App.js Bug

- README.md
- back-end/app.js
- back-end/package-lock.json
- back-end/test/getUser.js
Get individual user unit test is mostly fine, but I'm getting a 400 invalid syntax error instead of a 404 not found error for invalid users when using mocked data. Not sure what the cause of that is; could use some help.
Fixes #215
> Get user unit test; one failing

- README.md
- back-end/MockData.js
- back-end/app.js
- back-end/test/getShowsTrakt.js
- back-end/test/home.js
- back-end/test/logout.js
> Unit tests for get trakt shows

- README.md
- back-end/app.js
- back-end/models/Show.js
- back-end/package-lock.json
- back-end/readme.txt
- front-end/package-lock.json
> 244 show model

- back-end/MockData.js
- back-end/app.js
- back-end/models/User.js
- back-end/test/patchUsers.js
> patch user validation

- back-end/app.js
- back-end/test/getUser.js
> Database Test for GET /tv_users/:id

- back-end/app.js
- back-end/test/getShowsTrakt.js
- back-end/test/getUsers.js
> Looks good, thanks Alma!
thank you!
> Replace next(err) with json response

- front-end/src/pages/IndividualShow.js
- front-end/src/pages/MyShows.js
- front-end/src/utils/DropdownStyles.js
#257 Styling for dropdown menus to better match the color scheme.
> #257 styling for dropdown menus

- README.md
- back-end/app.js
- back-end/package-lock.json
- back-end/package.json
- package-lock.json
> 326 patch db call

- back-end/app.js
- front-end/src/App.js
- front-end/src/components/Hamburger.js
- front-end/src/pages/ViewUsers.css
- front-end/src/pages/ViewUsers.js
> Display all users

- back-end/models/User.js
- front-end/src/pages/IndividualShow.js
- front-end/src/pages/MyShows.js
- front-end/src/pages/ViewUsers.css
- front-end/src/utils/Helpers.js
placeholder platform change, logo fix, styling fix for view users header
> Front-end fixes

- front-end/src/App.css
- front-end/src/components/Header.css
- front-end/src/components/Header.js
- front-end/src/components/HeaderLogo.css
- front-end/src/pages/AllShows.css
- front-end/src/pages/IndividualShow.css
- front-end/src/pages/MyShows.css
- front-end/src/pages/TermsOfService.css
ReactStickyHeader causes errors on page reload/refresh sometimes. Doesn't seem like something we can fix, so this is a (currently failing) attempt at creating our own sticky header.
This is unfinished but I'm putting it not as a draft in hopes that people can leave some feedback to help :(
> Replace ReactStickyHeader 

- README.md
- front-end/src/pages/AllShows.js
- front-end/src/pages/IndividualShow.js
- front-end/src/pages/Login.js
- front-end/src/pages/MyShows.js
- front-end/src/pages/Profile.js
- front-end/src/pages/Signup.js
- front-end/src/pages/ViewUsers.js
Reverts agile-dev-assignments/project-setup-team-hatsukaichi-dynamic#353
> Revert "Fix Bug with Back-End in Deployed Version"
